import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import dynamic from 'next/dynamic';
const BottomFooter = dynamic(() => import('@/app/components/common/BottomFooter'));
const BottomFooterMobile = dynamic(() => import('@/app/components/common/BottomFooterMobile'));


export const metadata: Metadata = {
  title: "Movie hub",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        {children}
        <BottomFooter className="hidden md:block" />
        <BottomFooterMobile className="block md:hidden" />
      </body>
    </html>
  );
}
